# Generated by Django 3.0.4 on 2020-08-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(max_length=10000, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('departement', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('status', models.IntegerField(choices=[(0, 'BLOCKED'), (1, 'ALLOWED')], max_length=1)),
                ('reason', models.CharField(max_length=200, blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrivedate', models.DateTimeField(verbose_name='Arríving Date')),
                ('campus', models.CharField(choices=[('G', 'GISHUSHU CAMPUS'), ('M', 'MASORO CAMPUS')], max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.Student')),
            ],
        ),
    ]
