# Generated by Django 3.0.4 on 2020-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20200809_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photoUrl',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
