# Generated by Django 3.0.4 on 2020-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20200815_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photoUrl',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
